
from enum import Enum
# =========================
# CONFIGURATION
# =========================
BASE_URL = "http://192.168.124.90:8080/api/commands"
SENSOR_BASE_URL = "http://192.168.124.90:8080/api/"

SERIAL_PORT = "COM3"
BAUD_RATE = 115200
SERIAL_TIMEOUT = 2
POLL_INTERVAL = 0.2

FRAME_SIZE = 8


# =========================
# ENUMS BACKEND
# =========================
class CommandType(Enum):
    ACTION = "ACTION"
    STATE = "STATE"


class CommandStatus(Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


# =========================
# PROTOCOLE BINAIRE
# =========================

# Index des champs
IDX_FRAME_TYPE = 0
IDX_COMMAND_ID = 1
IDX_DEVICE_ID = 2
IDX_COMMAND_NAME = 3
IDX_COMMAND_TYPE = 4
IDX_COMMAND_VALUE = 5
IDX_COMMAND_STATUS = 6
IDX_TTL = 7

# Frame types
FRAME_TYPE_GLOBAL_CONTROL = 0x00
FRAME_TYPE_HARDWARE_CONTROL = 0x01
FRAME_TYPE_ACK = 0x02
FRAME_TYPE_SENSOR_DATA = 0x03

# Global control
GLOBAL_POWER_ON = 0x01
GLOBAL_POWER_OFF = 0x02

# Device IDs
DEVICE_SYSTEM = 0x00
DEVICE_LIGHT = 0x01
DEVICE_HEATING = 0x02
DEVICE_VENTILATION = 0x03
DEVICE_RFID = 0x04
DEVICE_DHT11 = 0x05
DEVICE_BUZZER = 0x06
DEVICE_LCD = 0x07

# Command names
CMD_NO_OP = 0x00
CMD_TURN_ON = 0x01
CMD_TURN_OFF = 0x02
CMD_TOGGLE = 0x03
CMD_SET_VALUE = 0x04
CMD_READ_VALUE = 0x05
CMD_RESET = 0x06
CMD_ENABLE = 0x07
CMD_DISABLE = 0x08
CMD_HEARTBEAT = 0x09

# Command types
CMD_TYPE_ACTION = 0x01
CMD_TYPE_CONFIG = 0x02
CMD_TYPE_QUERY = 0x03
CMD_TYPE_SYSTEM = 0x04

# Command values
CMD_VALUE_NONE = 0x00
CMD_VALUE_ON = 0x01
CMD_VALUE_OFF = 0x02
CMD_VALUE_TRUE = 0x01
CMD_VALUE_FALSE = 0x02
CMD_VALUE_ENABLE = 0x01
CMD_VALUE_DISABLE = 0x02

# Status protocole
STATUS_PENDING = 0x00
STATUS_EXECUTED = 0x01
STATUS_FAILED = 0x02
STATUS_EXPIRED = 0x03
STATUS_REJECTED = 0x04

# Error codes
ERROR_NONE = 0x00
ERROR_COMMAND_UNKNOWN = 0x01
ERROR_DEVICE_UNREACHABLE = 0x02
ERROR_TIMEOUT = 0x03
ERROR_INVALID_VALUE = 0x04
ERROR_INVALID_DEVICE = 0x05
ERROR_INVALID_FRAME = 0x06
ERROR_HARDWARE_FAILURE = 0x07
ERROR_BUSY = 0x08

RESERVED_BYTE = 0x00
TTL_NO_EXPIRATION = 0x00


# =========================
# MAPPINGS METIER -> PROTOCOLE
# =========================
DEVICE_MAP = {
    "SYSTEM": DEVICE_SYSTEM,
    "LIGHT": DEVICE_LIGHT,
    "HEATING": DEVICE_HEATING,
    "VENTILATION": DEVICE_VENTILATION,
    "RFID": DEVICE_RFID,
    "DHT11": DEVICE_DHT11,
    "BUZZER": DEVICE_BUZZER,
    "LCD": DEVICE_LCD,
}

COMMAND_NAME_MAP = {
    "TURN_ON": CMD_TURN_ON,
    "LIGHT_ON": CMD_TURN_ON,
    "HEATING_ON": CMD_TURN_ON,
    "VENTILATION_ON": CMD_TURN_ON,

    "TURN_OFF": CMD_TURN_OFF,
    "LIGHT_OFF": CMD_TURN_OFF,
    "HEATING_OFF": CMD_TURN_OFF,
    "VENTILATION_OFF": CMD_TURN_OFF,

    "TOGGLE": CMD_TOGGLE,
    "SET_VALUE": CMD_SET_VALUE,
    "READ_VALUE": CMD_READ_VALUE,
    "RESET": CMD_RESET,
    "ENABLE": CMD_ENABLE,
    "DISABLE": CMD_DISABLE,
    "HEARTBEAT": CMD_HEARTBEAT,

    "START": CMD_ENABLE,
    "STOP": CMD_DISABLE,
    "GLOBAL_ON": CMD_ENABLE,
    "GLOBAL_OFF": CMD_DISABLE,
}

COMMAND_TYPE_MAP = {
    "ACTION": CMD_TYPE_ACTION,
    "STATE": CMD_TYPE_ACTION,
    "CONFIG": CMD_TYPE_CONFIG,
    "QUERY": CMD_TYPE_QUERY,
    "SYSTEM": CMD_TYPE_SYSTEM,
}

ERROR_LABELS = {
    ERROR_NONE: "NONE",
    ERROR_COMMAND_UNKNOWN: "COMMAND_UNKNOWN",
    ERROR_DEVICE_UNREACHABLE: "DEVICE_UNREACHABLE",
    ERROR_TIMEOUT: "TIMEOUT",
    ERROR_INVALID_VALUE: "INVALID_VALUE",
    ERROR_INVALID_DEVICE: "INVALID_DEVICE",
    ERROR_INVALID_FRAME: "INVALID_FRAME",
    ERROR_HARDWARE_FAILURE: "HARDWARE_FAILURE",
    ERROR_BUSY: "BUSY",
}
